name: mock_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 # general package
  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  flutter_svg: ^1.0.3
  theme_provider: 0.5.0


  # Provider + Stack pattern
  stacked: ^2.2.8
  provider: ^6.0.2
  stacked_services: ^0.8.13

  #dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.0

  # navigator
  auto_route: ^3.2.1

  # Network
  connectivity:
  http: ^0.13.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  auto_route_generator: ^3.2.1
  injectable_generator: ^1.5.2


  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/
    - assets/svg/
    - assets/icons/
    - assets/font/


  uses-material-design: true

